import { createFileRoute, Link, useParams } from "@tanstack/react-router";
import { motion, AnimatePresence } from "framer-motion";
import {
  Radar, RadarChart, PolarGrid, PolarAngleAxis, PolarRadiusAxis,
  ResponsiveContainer, LineChart, Line, XAxis, YAxis, Tooltip, BarChart, Bar,
  AreaChart, Area,
} from "recharts";
import { useState } from "react";
import { ChevronDown, TrendingUp, TrendingDown, ShieldAlert, CheckCircle2, ArrowRight, Sparkles, AlertTriangle, X, FileDown, Share2, BadgeCheck } from "lucide-react";
import { toast } from "sonner";
import { findMSME, formatINR, recommendedLimit, suggestedProducts, bandColor, bandHex } from "@/data/msmes";
import { ScoreGauge } from "@/components/ScoreGauge";
import { ScoreSimulator } from "@/components/ScoreSimulator";

export const Route = createFileRoute("/dashboard/$id")({
  head: ({ params }) => ({
    meta: [
      { title: `Health Score · ${params.id} · MSME Financial Health Card` },
      { name: "description", content: "Financial Health Score dashboard powered by alternate-data signals." },
    ],
  }),
  component: Dashboard,
});

const DIMS = [
  { key: "revenueStability", label: "Revenue Stability", short: "Revenue" },
  { key: "cashFlowHealth", label: "Cash Flow Health", short: "Cashflow" },
  { key: "compliance", label: "Compliance", short: "Compliance" },
  { key: "digitalFootprint", label: "Digital Footprint", short: "Digital" },
  { key: "debtBehavior", label: "Debt Behavior", short: "Debt" },
] as const;

function Dashboard() {
  const { id } = useParams({ from: "/dashboard/$id" });
  const m = findMSME(id);
  const [bannerOpen, setBannerOpen] = useState(true);

  if (!m) {
    return (
      <div className="max-w-3xl mx-auto py-16 text-center">
        <h1 className="text-2xl font-semibold">MSME not found</h1>
        <Link to="/portfolio" className="text-sm underline mt-2 inline-block">Back to portfolio</Link>
      </div>
    );
  }

  const radarData = DIMS.map((d) => ({ dim: d.short, score: m.scores[d.key] }));
  const limit = recommendedLimit(m);
  const products = suggestedProducts(m);
  const gaugeColor = bandHex(m.scores.overall);

  // 6-month score history (deterministic mock derived from current score)
  const historyLabels = ["6mo", "5mo", "4mo", "3mo", "2mo", "1mo", "Now"];
  const history = historyLabels.map((label, i) => {
    const base = m.scores.overall - 8 + Math.round(Math.sin(i * 1.2 + m.id.length) * 3) + i * (m.gst.qoqGrowthPct >= 0 ? 1.3 : -0.6);
    return { label, score: Math.max(20, Math.min(100, Math.round(base))) };
  });
  history[history.length - 1].score = m.scores.overall;
  const quarterDelta = m.scores.overall - history[history.length - 4].score;

  const hasRisk = m.risks.length >= 2 || m.gst.qoqGrowthPct < 0;
  const bannerText = m.gst.qoqGrowthPct < 0
    ? `Cash flow dipped ${Math.abs(m.gst.qoqGrowthPct)}% this quarter — view details`
    : m.risks[0];

  const exportPdf = async () => {
    try {
      const { jsPDF } = await import("jspdf");
      const doc = new jsPDF({ unit: "pt", format: "a4" });
      doc.setFillColor(26, 58, 108);
      doc.rect(0, 0, 595, 80, "F");
      doc.setTextColor(255, 255, 255);
      doc.setFontSize(18);
      doc.text("MSME Financial Health Card", 40, 40);
      doc.setFontSize(11);
      doc.text("Alternate-data credit assessment", 40, 60);
      doc.setTextColor(20, 20, 20);
      doc.setFontSize(14);
      doc.text(m.businessName, 40, 120);
      doc.setFontSize(10);
      doc.setTextColor(90, 90, 90);
      doc.text(`${m.sector} · ${m.city} · ${m.yearsInOperation} yrs · GSTIN ${m.gstin}`, 40, 138);
      doc.setFontSize(36);
      doc.setTextColor(13, 148, 136);
      doc.text(`${m.scores.overall}/100`, 40, 190);
      doc.setFontSize(10);
      doc.setTextColor(60, 60, 60);
      let y = 220;
      doc.text("Dimension scores:", 40, y); y += 16;
      DIMS.forEach((d) => { doc.text(`  · ${d.label}: ${m.scores[d.key]}`, 50, y); y += 14; });
      y += 8; doc.text("Recommended credit limit: " + formatINR(limit), 40, y); y += 20;
      doc.text("Strengths:", 40, y); y += 14;
      m.strengths.forEach((s) => { doc.text(`  · ${s}`, 50, y, { maxWidth: 500 }); y += 14; });
      y += 6; doc.text("Risk flags:", 40, y); y += 14;
      (m.risks.length ? m.risks : ["None flagged"]).forEach((s) => { doc.text(`  · ${s}`, 50, y, { maxWidth: 500 }); y += 14; });
      doc.setFontSize(9); doc.setTextColor(120, 120, 120);
      doc.text("Generated by VittSetu · Prototype · Confidential", 40, 800);
      doc.save(`${m.businessName.replace(/\s+/g, "_")}_HealthCard.pdf`);
      toast.success("Report exported as PDF");
    } catch (e) {
      console.error(e);
      toast.error("Could not export PDF — please try again");
    }
  };

  const share = async () => {
    const url = typeof window !== "undefined" ? window.location.href : "";
    try { await navigator.clipboard.writeText(url); toast.success("Share link copied to clipboard"); }
    catch { toast("Link ready to share", { description: url }); }
  };

  return (
    <div className="max-w-7xl mx-auto px-4 sm:px-6 py-8">
      <AnimatePresence>
        {hasRisk && bannerOpen && (
          <motion.div initial={{ opacity: 0, y: -8 }} animate={{ opacity: 1, y: 0 }} exit={{ opacity: 0, y: -8 }}
            className="mb-4 rounded-xl border p-3 flex items-start gap-3"
            style={{ borderColor: "#f59e0b55", background: "#fffbeb" }}>
            <AlertTriangle className="h-4 w-4 mt-0.5 text-amber-600 shrink-0" />
            <div className="flex-1 text-sm text-amber-900">
              <span className="font-semibold">Risk alert · </span>{bannerText}
            </div>
            <button onClick={() => setBannerOpen(false)} className="text-amber-700 hover:text-amber-900"><X className="h-4 w-4" /></button>
          </motion.div>
        )}
      </AnimatePresence>

      {/* header */}
      <div className="flex flex-wrap items-end justify-between gap-4 mb-6">
        <div>
          <div className="text-xs uppercase tracking-widest text-muted-foreground">Financial Health Card</div>
          <div className="mt-1 flex items-center gap-3 flex-wrap">
            <h1 className="text-3xl font-bold" style={{ color: "#1a3a6c" }}>{m.businessName}</h1>
            <span className="group relative inline-flex items-center gap-1 px-2 py-0.5 rounded-full text-[11px] font-semibold border" style={{ borderColor: "#0d948855", color: "#0d9488", background: "#0d94880f" }}>
              <BadgeCheck className="h-3.5 w-3.5" /> Alternate-Data Verified
              <span className="absolute top-full mt-1 left-0 w-64 p-2 rounded-md bg-[#1a3a6c] text-white text-[11px] leading-snug opacity-0 group-hover:opacity-100 pointer-events-none transition-opacity z-10 shadow-lg">
                Verified via GST + UPI + AA + EPFO — no physical documents required.
              </span>
            </span>
          </div>
          <div className="mt-1 text-sm text-muted-foreground">
            {m.sector} · {m.city} · {m.yearsInOperation} yrs · GSTIN {m.gstin}
          </div>
        </div>
        <div className="flex items-center gap-2">
          <button onClick={exportPdf} className="inline-flex items-center gap-1.5 px-3 py-2 rounded-lg text-sm font-medium border border-border bg-white hover:bg-secondary">
            <FileDown className="h-3.5 w-3.5" /> Export PDF
          </button>
          <button onClick={share} className="inline-flex items-center gap-1.5 px-3 py-2 rounded-lg text-sm font-medium border border-border bg-white hover:bg-secondary">
            <Share2 className="h-3.5 w-3.5" /> Share
          </button>
          <Link to="/portfolio" className="text-sm text-muted-foreground hover:text-foreground">← Portfolio</Link>
          <Link
            to="/decision/$id"
            params={{ id: m.id }}
            className="inline-flex items-center gap-1.5 px-4 py-2 rounded-lg text-white font-medium shadow-sm"
            style={{ background: "#1a3a6c" }}
          >
            Proceed to Decision <ArrowRight className="h-4 w-4" />
          </Link>
        </div>
      </div>

      {/* score + radar hero */}
      <div className="grid lg:grid-cols-5 gap-4 mb-4">
        <motion.div
          initial={{ opacity: 0, y: 10 }}
          animate={{ opacity: 1, y: 0 }}
          className="lg:col-span-2 rounded-2xl border border-border bg-white p-6 flex flex-col items-center justify-center shadow-[var(--shadow-card)] relative overflow-hidden"
        >
          <motion.div
            aria-hidden
            animate={{ opacity: [0.15, 0.35, 0.15] }}
            transition={{ duration: 3, repeat: Infinity, ease: "easeInOut" }}
            className="absolute inset-0 -z-0 pointer-events-none"
            style={{ background: `radial-gradient(240px 240px at 50% 45%, ${gaugeColor}33, transparent 65%)` }}
          />
          <div className="text-xs uppercase tracking-widest text-muted-foreground mb-4">Overall Health Score</div>
          <div className="relative"><ScoreGauge score={m.scores.overall} /></div>
          <div className="mt-3 inline-flex items-center gap-1.5 text-xs font-medium" style={{ color: quarterDelta >= 0 ? "#059669" : "#dc2626" }}>
            {quarterDelta >= 0 ? <TrendingUp className="h-3.5 w-3.5" /> : <TrendingDown className="h-3.5 w-3.5" />}
            {quarterDelta >= 0 ? "+" : ""}{quarterDelta} pts since last quarter
          </div>
          <div className="mt-4 text-sm text-center text-muted-foreground max-w-xs">
            Composite of GST filings, UPI velocity, AA cashflow and EPFO consistency.
          </div>
        </motion.div>

        <motion.div
          initial={{ opacity: 0, y: 10 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ delay: 0.1 }}
          className="lg:col-span-3 rounded-2xl border border-border bg-white p-6 shadow-[var(--shadow-card)]"
        >
          <div className="flex items-center justify-between mb-2">
            <div>
              <div className="text-xs uppercase tracking-widest text-muted-foreground">5-Dimension Profile</div>
              <div className="text-sm font-medium" style={{ color: "#1a3a6c" }}>Multidimensional health map</div>
            </div>
          </div>
          <div className="h-[300px]">
            <ResponsiveContainer width="100%" height="100%">
              <RadarChart data={radarData} outerRadius="78%">
                <PolarGrid stroke="#e5e7eb" />
                <PolarAngleAxis dataKey="dim" tick={{ fontSize: 12, fill: "#475569" }} />
                <PolarRadiusAxis angle={90} domain={[0, 100]} tick={{ fontSize: 10, fill: "#94a3b8" }} />
                <Radar name="Score" dataKey="score" stroke="#0d9488" fill="#0d9488" fillOpacity={0.28} strokeWidth={2} isAnimationActive animationDuration={1200} animationEasing="ease-out" />
              </RadarChart>
            </ResponsiveContainer>
          </div>
          <div className="grid grid-cols-5 gap-2 mt-2">
            {DIMS.map((d) => (
              <div key={d.key} className="text-center">
                <div className="text-[10px] uppercase tracking-wider text-muted-foreground">{d.short}</div>
                <div className="text-lg font-bold" style={{ color: bandHex(m.scores[d.key]) }}>{m.scores[d.key]}</div>
              </div>
            ))}
          </div>
        </motion.div>
      </div>

      {/* 6-month score history */}
      <div className="rounded-2xl border border-border bg-white p-5 shadow-[var(--shadow-card)] mb-4">
        <div className="flex items-end justify-between mb-2">
          <div>
            <div className="text-xs uppercase tracking-widest text-muted-foreground">Score history</div>
            <div className="text-sm font-medium" style={{ color: "#1a3a6c" }}>6-month trend</div>
          </div>
          <div className="inline-flex items-center gap-1.5 text-xs font-medium" style={{ color: quarterDelta >= 0 ? "#059669" : "#dc2626" }}>
            {quarterDelta >= 0 ? <TrendingUp className="h-3.5 w-3.5" /> : <TrendingDown className="h-3.5 w-3.5" />}
            {quarterDelta >= 0 ? "+" : ""}{quarterDelta} pts since last quarter
          </div>
        </div>
        <div className="h-[180px]">
          <ResponsiveContainer width="100%" height="100%">
            <AreaChart data={history}>
              <defs>
                <linearGradient id="hist" x1="0" y1="0" x2="0" y2="1">
                  <stop offset="0%" stopColor="#0d9488" stopOpacity={0.35} />
                  <stop offset="100%" stopColor="#0d9488" stopOpacity={0} />
                </linearGradient>
              </defs>
              <XAxis dataKey="label" tick={{ fontSize: 11, fill: "#94a3b8" }} />
              <YAxis domain={[0, 100]} tick={{ fontSize: 11, fill: "#94a3b8" }} />
              <Tooltip contentStyle={{ fontSize: 12, borderRadius: 8 }} />
              <Area type="monotone" dataKey="score" stroke="#0d9488" strokeWidth={2.5} fill="url(#hist)" />
            </AreaChart>
          </ResponsiveContainer>
        </div>
      </div>

      {/* strengths / risks / recommendation */}
      <div className="grid lg:grid-cols-3 gap-4 mb-4">
        <div className="rounded-2xl border border-border bg-white p-5 shadow-[var(--shadow-card)]">
          <div className="flex items-center gap-2 mb-3">
            <CheckCircle2 className="h-4 w-4 text-emerald-600" />
            <div className="text-sm font-semibold" style={{ color: "#1a3a6c" }}>Strengths</div>
          </div>
          <ul className="space-y-2 text-sm">
            {m.strengths.map((s, i) => (
              <li key={i} className="flex gap-2">
                <span className="mt-1.5 h-1.5 w-1.5 rounded-full bg-emerald-500 shrink-0" />
                <span>{s}</span>
              </li>
            ))}
          </ul>
        </div>
        <div className="rounded-2xl border border-border bg-white p-5 shadow-[var(--shadow-card)]">
          <div className="flex items-center gap-2 mb-3">
            <ShieldAlert className="h-4 w-4 text-red-600" />
            <div className="text-sm font-semibold" style={{ color: "#1a3a6c" }}>Risk Flags</div>
          </div>
          <ul className="space-y-2 text-sm">
            {m.risks.length === 0 && <li className="text-muted-foreground text-xs">No material risk flags detected.</li>}
            {m.risks.map((s, i) => (
              <li key={i} className="flex gap-2">
                <span className="mt-1.5 h-1.5 w-1.5 rounded-full bg-red-500 shrink-0" />
                <span>{s}</span>
              </li>
            ))}
          </ul>
        </div>
        <div
          className="rounded-2xl p-5 shadow-[var(--shadow-card)] text-white"
          style={{ background: "linear-gradient(135deg,#1a3a6c 0%, #0d9488 100%)" }}
        >
          <div className="flex items-center gap-2 mb-3">
            <Sparkles className="h-4 w-4" />
            <div className="text-sm font-semibold">Underwriter Recommendation</div>
          </div>
          <div className="text-xs opacity-80">Suggested credit limit</div>
          <div className="text-3xl font-bold mt-0.5">{formatINR(limit)}</div>
          <div className="text-xs opacity-80 mt-3 mb-1">Loan products to consider</div>
          <ul className="text-sm space-y-1">
            {products.map((p) => (
              <li key={p} className="flex items-center gap-1.5">
                <span className="h-1 w-1 rounded-full bg-white/80" /> {p}
              </li>
            ))}
          </ul>
        </div>
      </div>

      {/* scenario simulator */}
      <div className="mb-4">
        <ScoreSimulator msme={m} />
      </div>

      {/* dimension deep dives */}
      <div className="space-y-3">
        {DIMS.map((d, i) => (
          <DimensionCard key={d.key} msme={m} dim={d} defaultOpen={i === 0} />
        ))}
      </div>

      <div className="mt-6 rounded-xl border border-dashed border-border bg-white p-4 text-xs text-muted-foreground">
        This isn't just a credit score — it's a financial inclusion tool. Alternate signals let banks say <span className="font-semibold text-foreground">yes</span> to good businesses that formal documents would say no to.
      </div>
    </div>
  );
}

function DimensionCard({
  msme, dim, defaultOpen,
}: {
  msme: ReturnType<typeof findMSME> & object;
  dim: (typeof DIMS)[number];
  defaultOpen?: boolean;
}) {
  const [open, setOpen] = useState(!!defaultOpen);
  const score = msme.scores[dim.key];
  const color = bandHex(score);
  const insights = msme.insights[dim.key];

  const chartData =
    dim.key === "revenueStability"
      ? msme.gst.revenueTrend
      : dim.key === "digitalFootprint"
        ? msme.upi.trend.map((t) => ({ month: t.month, revenue: t.count }))
        : dim.key === "cashFlowHealth"
          ? msme.gst.revenueTrend.map((t) => ({ month: t.month, revenue: Math.round(t.revenue * 0.85) }))
          : dim.key === "compliance"
            ? msme.gst.revenueTrend.map((t, i) => ({ month: t.month, revenue: 60 + ((i * 7 + score) % 40) }))
            : msme.gst.revenueTrend.map((t, i) => ({ month: t.month, revenue: Math.max(20, score - 10 + ((i * 3) % 15)) }));

  const isBar = dim.key === "digitalFootprint";

  return (
    <div className="rounded-2xl border border-border bg-white overflow-hidden shadow-[var(--shadow-card)]">
      <button
        onClick={() => setOpen(!open)}
        className="w-full flex items-center justify-between p-4 sm:p-5 text-left hover:bg-secondary/30 transition-colors"
      >
        <div className="flex items-center gap-3">
          <div
            className="h-10 w-10 rounded-lg flex items-center justify-center font-bold text-sm"
            style={{ background: `${color}18`, color }}
          >
            {score}
          </div>
          <div>
            <div className="font-semibold" style={{ color: "#1a3a6c" }}>{dim.label}</div>
            <div className="text-xs text-muted-foreground">
              {insights[0]}
            </div>
          </div>
        </div>
        <ChevronDown className={`h-4 w-4 transition-transform ${open ? "rotate-180" : ""}`} />
      </button>
      {open && (
        <motion.div
          initial={{ opacity: 0, height: 0 }}
          animate={{ opacity: 1, height: "auto" }}
          className="border-t border-border grid md:grid-cols-2 gap-4 p-4 sm:p-5"
        >
          <div className="h-[200px] rounded-lg bg-secondary/40 p-3">
            <div className="text-[11px] uppercase tracking-wider text-muted-foreground mb-2">
              {dim.key === "digitalFootprint" ? "UPI Monthly Transactions" : "12-month trend"}
            </div>
            <ResponsiveContainer width="100%" height="85%">
              {isBar ? (
                <BarChart data={chartData}>
                  <XAxis dataKey="month" tick={{ fontSize: 10, fill: "#94a3b8" }} />
                  <YAxis tick={{ fontSize: 10, fill: "#94a3b8" }} />
                  <Tooltip contentStyle={{ fontSize: 12, borderRadius: 8 }} />
                  <Bar dataKey="revenue" fill="#0d9488" radius={[4, 4, 0, 0]} />
                </BarChart>
              ) : (
                <LineChart data={chartData}>
                  <XAxis dataKey="month" tick={{ fontSize: 10, fill: "#94a3b8" }} />
                  <YAxis tick={{ fontSize: 10, fill: "#94a3b8" }} />
                  <Tooltip contentStyle={{ fontSize: 12, borderRadius: 8 }} />
                  <Line type="monotone" dataKey="revenue" stroke={color} strokeWidth={2.5} dot={false} />
                </LineChart>
              )}
            </ResponsiveContainer>
          </div>
          <div>
            <div className="text-[11px] uppercase tracking-wider text-muted-foreground mb-2 flex items-center gap-1.5">
              <TrendingUp className="h-3 w-3" /> Insights
            </div>
            <ul className="space-y-2 text-sm">
              {insights.map((it, i) => (
                <li key={i} className="flex gap-2">
                  <span className="mt-1.5 h-1.5 w-1.5 rounded-full shrink-0" style={{ background: color }} />
                  <span>{it}</span>
                </li>
              ))}
            </ul>
          </div>
        </motion.div>
      )}
    </div>
  );
}

// noop use for badge helper to avoid unused import
void bandColor;